# Generated by Django 3.2.4 on 2023-06-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
